// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1WT03hl2WRjDOUBwellMTiyHQwxJzgHI',
    appId: '1:192275732807:web:eb36a4897444a9b29d9462',
    messagingSenderId: '192275732807',
    projectId: 'foodevenproject',
    authDomain: 'foodevenproject.firebaseapp.com',
    storageBucket: 'foodevenproject.appspot.com',
    measurementId: 'G-9BF5EVFNW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAEB2HTeSyEIRmT8zhgvEDSmB3U7AOW0',
    appId: '1:192275732807:android:ed61c8fbe93fffda9d9462',
    messagingSenderId: '192275732807',
    projectId: 'foodevenproject',
    storageBucket: 'foodevenproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2y1e6QvbrZfcSeW7kTw_CSZXaDWlxuM',
    appId: '1:192275732807:ios:cc9d97ec7d752b9b9d9462',
    messagingSenderId: '192275732807',
    projectId: 'foodevenproject',
    storageBucket: 'foodevenproject.appspot.com',
    iosBundleId: 'com.example.foodevenproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2y1e6QvbrZfcSeW7kTw_CSZXaDWlxuM',
    appId: '1:192275732807:ios:97c1936f021b1a019d9462',
    messagingSenderId: '192275732807',
    projectId: 'foodevenproject',
    storageBucket: 'foodevenproject.appspot.com',
    iosBundleId: 'com.example.foodevenproject.RunnerTests',
  );
}
